# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bonsai < Formula
  desc "Cheap, opinionated Kubernetes provisioner for small teams (AWS, Hetzner)"
  homepage "https://github.com/badriram/bonsai"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/badriram/bonsai/releases/download/v0.1.0/bonsai_0.1.0_darwin_amd64.tar.gz"
      sha256 "f5882a2664df5baa7ff80e9f91d00231d8399ecd819134a41c6578f8eb6974cc"

      define_method(:install) do
        bin.install "bonsai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/badriram/bonsai/releases/download/v0.1.0/bonsai_0.1.0_darwin_arm64.tar.gz"
      sha256 "4232b7c76c751eb768fcc8b9df27eb75352887ac8f06fc667c1bf9719c24eee4"

      define_method(:install) do
        bin.install "bonsai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/badriram/bonsai/releases/download/v0.1.0/bonsai_0.1.0_linux_amd64.tar.gz"
      sha256 "1335e33fb5b683b576f3bc91d23301cf7505658502357576a353c5b1df0807f7"
      define_method(:install) do
        bin.install "bonsai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/badriram/bonsai/releases/download/v0.1.0/bonsai_0.1.0_linux_arm64.tar.gz"
      sha256 "5abe229e525203ce9f0eda6a5e42e6f78ba622d31a7250f3f104973c670b72d7"
      define_method(:install) do
        bin.install "bonsai"
      end
    end
  end

  test do
    system "#{bin}/bonsai", "--version"
  end
end
