# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bonsai < Formula
  desc "Cheap, opinionated Kubernetes provisioner for small teams (AWS, Hetzner)"
  homepage "https://github.com/badriram/bonsai"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/badriram/bonsai/releases/download/v0.2.0/bonsai_0.2.0_darwin_amd64.tar.gz"
      sha256 "cad95285bbfdfbb5161d596a4ef9736987d8788dcf66d8709cfbc4eb241bd58c"

      define_method(:install) do
        bin.install "bonsai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/badriram/bonsai/releases/download/v0.2.0/bonsai_0.2.0_darwin_arm64.tar.gz"
      sha256 "d5fe04a49caf8f3f35f8cb1bf2a7b08c58edbabda8850bf6179ed0c3f606646e"

      define_method(:install) do
        bin.install "bonsai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/badriram/bonsai/releases/download/v0.2.0/bonsai_0.2.0_linux_amd64.tar.gz"
      sha256 "741358225d7e7ef22d108084fe3ef1ac54515fa937ba52aac38874a8c9e9338c"
      define_method(:install) do
        bin.install "bonsai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/badriram/bonsai/releases/download/v0.2.0/bonsai_0.2.0_linux_arm64.tar.gz"
      sha256 "36979f34c9ca95d35c4fb99344a5d50c05d9c2880d2a1b0903e4f5d1bb522b09"
      define_method(:install) do
        bin.install "bonsai"
      end
    end
  end

  test do
    system "#{bin}/bonsai", "--version"
  end
end
