# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bonsai < Formula
  desc "Cheap, opinionated Kubernetes provisioner for small teams (AWS, Hetzner)"
  homepage "https://github.com/badriram/bonsai"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/badriram/bonsai/releases/download/v0.2.1/bonsai_0.2.1_darwin_amd64.tar.gz"
      sha256 "914477a80580828dd113300d2d560ae3046fb4ce63acdf33cdd575d6e8b5be89"

      define_method(:install) do
        bin.install "bonsai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/badriram/bonsai/releases/download/v0.2.1/bonsai_0.2.1_darwin_arm64.tar.gz"
      sha256 "633130add9c2e3d2c4509d1c423e199cc3d6f2c9d6b4e54bc85689add2886d66"

      define_method(:install) do
        bin.install "bonsai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/badriram/bonsai/releases/download/v0.2.1/bonsai_0.2.1_linux_amd64.tar.gz"
      sha256 "6d0034328c4fbee044c279dd554de37590c20b5b2e83dc280b6b77f7c3290cb7"
      define_method(:install) do
        bin.install "bonsai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/badriram/bonsai/releases/download/v0.2.1/bonsai_0.2.1_linux_arm64.tar.gz"
      sha256 "a62a4eef08e2120ac9a75dea3cb54a1e431a27724b0eb9a94f5f9d80ea0c3460"
      define_method(:install) do
        bin.install "bonsai"
      end
    end
  end

  test do
    system "#{bin}/bonsai", "--version"
  end
end
